services:
  db_development:
    image: postgres:17.6
    container_name: postgres-db-development
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "postgres_development:/var/lib/postgresql/data"
  rabbitmq_development:
    image: rabbitmq:3-management
    container_name: rabbitmq-development
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_CONSOLE_PORT}:${RABBITMQ_CONSOLE_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_development:/var/lib/rabbitmq
  minio_development:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio-development
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_development:/data
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
  redis_development:
    image: redis:7
    container_name: redis-development
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: [ "redis-server", "--requirepass", "${REDIS_SECRET_KEY}" ]
volumes:
  postgres_development:
  rabbitmq_development:
  minio_development:
