import "./globals.css";
import type { Metadata } from "next";
import { RootLayoutWrapper } from "./RootLayoutWrapper";

export const metadata: Metadata = {
  title: "Image Hub",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-br">
      <body>
        <RootLayoutWrapper>
          {children}
        </RootLayoutWrapper>
      </body>
    </html>
  )
}
